#### Assignment :  NumPy 
#### Pravinsingh Korekar
##### 8767135153
##### pravinkorekar6@gmail.com

# Theoretical Questions

### 1. Explain the purpose and advantage of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations.


NumPy, short for Numerical Python, is a fundamental library for scientific computing and data analysis in Python. Here are some key purposes and advantages of using NumPy:

**Purpose of NumPy**
1. **Efficient Array Operations**: NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
2. **Foundation for Other Libraries**: Many other scientific computing libraries, such as Pandas, SciPy, and Matplotlib, are built on top of NumPy, making it a cornerstone of the Python data science ecosystem¹.
3. **Numerical Computations**: It is designed for high-performance numerical computations, making it ideal for tasks that require heavy mathematical operations.

**Advantages of NumPy**
1. **Performance**: NumPy is significantly faster than Python lists because it uses optimized, pre-compiled C code. This allows for efficient memory usage and quick execution of operations.
2. **Vectorization**: NumPy allows for vectorized operations, which means you can perform element-wise operations on entire arrays without the need for explicit loops. This not only makes the code more readable but also enhances performance.
3. **Broadcasting**: This feature allows NumPy to handle arithmetic operations on arrays of different shapes, making it easier to perform operations without needing to reshape or replicate arrays.
4. **Integration**: NumPy integrates seamlessly with other libraries and tools in the Python ecosystem, making it versatile for various applications in data analysis, machine learning, and scientific research.

**Enhancing Python's Capabilities**
- **Memory Efficiency**: NumPy arrays consume less memory compared to Python lists, which is crucial when working with large datasets⁴.
- **Mathematical Functions**: It provides a wide range of mathematical functions that are optimized for performance, enabling complex calculations to be performed efficiently.
- **Data Handling**: NumPy's array-oriented computing allows for efficient handling and manipulation of large datasets, which is essential for data analysis and machine learning tasks.

### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other

Certainly! Both `np.mean()` and `np.average()` functions in NumPy are used to calculate the average of an array, but they have some differences in functionality and use cases.

**np.mean()**

- **Purpose**: Calculates the arithmetic mean (average) of the elements along the specified axis.
- **Syntax**: `np.mean(arr, axis=None)`
- **Weights**: Does not support weights; all elements are considered equally.
- **Use Case**: Use `np.mean()` when you need a simple arithmetic mean without considering the relative importance of elements.

**np.average()**

- **Purpose**: Calculates the weighted average of the elements along the specified axis.
- **Syntax**: `np.average(arr, axis=None, weights=None)`
- **Weights**: Supports weights; you can pass an array of weights to calculate a weighted average.
- **Use Case**: Use `np.average()` when you need to calculate a weighted average, where some elements contribute more to the average than others.

**Comparison**

1. **Arithmetic Mean**:
   - Both functions can calculate the arithmetic mean if no weights are provided.
   - Example:
     ```python
     import numpy as np
     data = [1, 2, 3, 4, 5]
     print(np.mean(data))  # Output: 3.0
     print(np.average(data))  # Output: 3.0
     ```

2. **Weighted Average**:
   - `np.mean()` cannot handle weights.
   - `np.average()` can handle weights, making it more flexible for specific use cases.
   - Example:
     ```python
     weights = [0.1, 0.2, 0.3, 0.4, 0.5]
     print(np.average(data, weights=weights))  # Output: 3.6666666666666665
     ```

**When to Use Which**

- **Use `np.mean()`**:
  - When you need a straightforward arithmetic mean.
  - When all elements should be treated equally.
  - For simplicity and slightly better performance in cases where weights are not needed.

- **Use `np.average()`**:
  - When you need to calculate a weighted average.
  - When different elements have different levels of importance or frequency.
  - For more complex averaging scenarios where weights are a factor.


### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

Reversing a NumPy array can be done using several methods, depending on the axis along which you want to reverse the array. Here are some common methods:

**1. Using `np.flip()`**
The `np.flip()` function reverses the order of elements in an array along the specified axis.

**1D Array Example**
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)
print(reversed_arr)  # Output: [5 4 3 2 1]
```

**2D Array Example**
```python
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
reversed_arr_2d = np.flip(arr_2d, axis=0)  # Reverse along the first axis (rows)
print(reversed_arr_2d)
# Output:
# [[4 5 6]
#  [1 2 3]]

reversed_arr_2d = np.flip(arr_2d, axis=1)  # Reverse along the second axis (columns)
print(reversed_arr_2d)
# Output:
# [[3 2 1]
#  [6 5 4]]
```

**2. Using Slicing**
You can use Python's slicing syntax to reverse arrays.

**1D Array Example**
```python
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]
```

**2D Array Example**
```python
reversed_arr_2d = arr_2d[::-1, :]  # Reverse along the first axis (rows)
print(reversed_arr_2d)
# Output:
# [[4 5 6]
#  [1 2 3]]

reversed_arr_2d = arr_2d[:, ::-1]  # Reverse along the second axis (columns)
print(reversed_arr_2d)
# Output:
# [[3 2 1]
#  [6 5 4]]
```

**3. Using `np.flipud()` and `np.fliplr()`**
These functions are specialized for flipping arrays vertically and horizontally.

**2D Array Example**
```python
reversed_arr_2d = np.flipud(arr_2d)  # Flip up-down (vertically)
print(reversed_arr_2d)
# Output:
# [[4 5 6]
#  [1 2 3]]

reversed_arr_2d = np.fliplr(arr_2d)  # Flip left-right (horizontally)
print(reversed_arr_2d)
# Output:
# [[3 2 1]
#  [6 5 4]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

To determine the data type of elements in a NumPy array, you can use the `dtype` attribute. This attribute provides information about the data type of the array's elements.

**Determining Data Type**
Here's how you can check the data type of elements in a NumPy array:

**Example**
```python
import numpy as np

# Creating an array of integers
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64

# Creating an array of floats
arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype)  # Output: float64

# Creating an array of strings
arr_str = np.array(['a', 'b', 'c'])
print(arr_str.dtype)  # Output: <U1
```

**Importance of Data Types in Memory Management and Performance**

1. **Memory Efficiency**:
   - **Compact Storage**: Different data types consume different amounts of memory. For example, an `int32` array uses less memory than an `int64` array. Choosing the appropriate data type can save memory, especially when dealing with large datasets.
   - **Example**:
     ```python
     arr_int32 = np.array([1, 2, 3], dtype='int32')
     arr_int64 = np.array([1, 2, 3], dtype='int64')
     print(arr_int32.nbytes)  # Output: 12 (3 elements * 4 bytes each)
     print(arr_int64.nbytes)  # Output: 24 (3 elements * 8 bytes each)
     ```

2. **Performance**:
   - **Computation Speed**: Operations on arrays with smaller data types (e.g., `int32` vs. `int64`) are generally faster because they require less memory bandwidth and cache usage.
   - **Vectorized Operations**: NumPy is optimized for vectorized operations, which are more efficient when the data types are consistent and appropriately chosen.
   - **Example**:
     ```python
     arr_large = np.random.randint(0, 100, size=1000000, dtype='int32')
     %timeit np.sum(arr_large)  # Faster with int32
     arr_large = np.random.randint(0, 100, size=1000000, dtype='int64')
     %timeit np.sum(arr_large)  # Slower with int64
     ```

3. **Compatibility**:
   - **Interoperability**: Ensuring the correct data type is crucial when interfacing with other libraries or systems that expect data in a specific format.
   - **Precision**: Choosing the right data type ensures that calculations are performed with the required precision, avoiding issues like overflow or underflow.

### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

**Defining ndarrays in NumPy**
An `ndarray` (N-dimensional array) in NumPy is a powerful data structure that represents a multi-dimensional, homogeneous array of fixed-size items. Here are some key features and characteristics of `ndarrays`:

**Key Features of ndarrays**

1. **Multi-Dimensional**:
   - `ndarrays` can have any number of dimensions, allowing for the storage and manipulation of multi-dimensional data.
   - Example:
     ```python
     import numpy as np
     arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
     print(arr_2d.shape)  # Output: (2, 3)
     ```

2. **Homogeneous Data**:
   - All elements in an `ndarray` must be of the same data type, ensuring consistency and efficiency in operations.
   - Example:
     ```python
     arr = np.array([1, 2, 3], dtype=np.int32)
     print(arr.dtype)  # Output: int32
     ```

3. **Fixed Size**:
   - Once created, the size of an `ndarray` is fixed. You cannot change its size, but you can create a new array with a different size.
   - Example:
     ```python
     arr = np.array([1, 2, 3])
     print(arr.size)  # Output: 3
     ```

4. **Efficient Memory Usage**:
   - `ndarrays` are stored in contiguous blocks of memory, making them highly efficient for numerical computations.
   - Example:
     ```python
     arr = np.array([1, 2, 3])
     print(arr.nbytes)  # Output: 12 (3 elements * 4 bytes each for int32)
     ```

5. **Vectorized Operations**:
   - NumPy supports vectorized operations, allowing for element-wise operations without explicit loops, which enhances performance.
   - Example:
     ```python
     arr = np.array([1, 2, 3])
     print(arr * 2)  # Output: [2 4 6]
     ```

6. **Broadcasting**:
   - Broadcasting allows NumPy to perform operations on arrays of different shapes by expanding them to a common shape.
   - Example:
     ```python
     arr1 = np.array([1, 2, 3])
     arr2 = np.array([[1], [2], [3]])
     print(arr1 + arr2)
     # Output:
     # [[2 3 4]
     #  [3 4 5]
     #  [4 5 6]]
     ```

**Differences from Standard Python Lists**

1. **Homogeneity**:
   - **ndarrays**: All elements must be of the same data type.
   - **Python Lists**: Can contain elements of different data types.
   - Example:
     ```python
     list_example = [1, 'a', 3.0]
     ```

2. **Performance**:
   - **ndarrays**: Optimized for numerical operations and are much faster due to contiguous memory allocation and vectorized operations.
   - **Python Lists**: Slower for numerical operations as they are not optimized for such tasks.
   - Example:
     ```python
     import time
     arr = np.arange(1000000)
     list_example = list(range(1000000))

     start = time.time()
     arr_sum = np.sum(arr)
     print("NumPy sum:", time.time() - start)

     start = time.time()
     list_sum = sum(list_example)
     print("List sum:", time.time() - start)
     ```

3. **Memory Efficiency**:
   - **ndarrays**: More memory-efficient due to fixed-size and homogeneous data.
   - **Python Lists**: Less memory-efficient as they store references to objects, which can be of different types.
   - Example:
     ```python
     arr = np.array([1, 2, 3])
     list_example = [1, 2, 3]
     print(arr.nbytes)  # Output: 12
     ```

4. **Functionality**:
   - **ndarrays**: Provide a wide range of mathematical functions and operations specifically designed for numerical data.
   - **Python Lists**: General-purpose containers with basic functionalities.
   - Example:
     ```python
     arr = np.array([1, 2, 3])
     print(np.mean(arr))  # Output: 2.0
     ```

### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations
NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. Here are some key reasons why:

**1. Memory Efficiency**
- **Contiguous Memory Allocation**: NumPy arrays are stored in contiguous blocks of memory, which improves cache efficiency and reduces memory overhead. This is in contrast to Python lists, which store elements as separate objects with additional type information and pointers¹.
- **Fixed Data Types**: All elements in a NumPy array are of the same data type, allowing for more compact storage. Python lists, on the other hand, can store elements of different types, leading to higher memory consumption².

**2. Performance**
- **Vectorized Operations**: NumPy supports vectorized operations, which allow you to perform element-wise operations on entire arrays without explicit loops. This leads to significant speedups as the operations are implemented in optimized C code³.
  - **Example**:
    ```python
    import numpy as np
    arr = np.array([1, 2, 3, 4, 5])
    result = arr * 2  # Vectorized operation
    print(result)  # Output: [2 4 6 8 10]
    ```

- **Lower-Level Implementation**: NumPy operations are implemented in C and Fortran, which are lower-level and faster languages than Python. This results in faster execution of numerical computations⁴.

**3. Broadcasting**
- **Automatic Expansion**: NumPy's broadcasting feature allows it to perform operations on arrays of different shapes by automatically expanding them to a common shape. This eliminates the need for explicit loops and makes the code more concise and efficient².
  - **Example**:
    ```python
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([[1], [2], [3]])
    result = arr1 + arr2
    print(result)
    # Output:
    # [[2 3 4]
    #  [3 4 5]
    #  [4 5 6]]
    ```

**4. Advanced Mathematical Functions**
- **Rich Functionality**: NumPy provides a wide range of mathematical and statistical functions that are optimized for performance. These functions are not available in standard Python lists.
  - **Example**:
    ```python
    arr = np.array([1, 2, 3, 4, 5])
    mean = np.mean(arr)
    print(mean)  # Output: 3.0
    ```

**5. Ease of Use**
- **Concise Syntax**: NumPy's syntax for operations is more concise and closer to mathematical notation, making the code easier to write and read².
  - **Example**:
    ```python
    arr = np.array([1, 2, 3, 4, 5])
    result = arr + 10
    print(result)  # Output: [11 12 13 14 15]
    ```

**Performance Comparison Example**
Here's a simple performance comparison between NumPy arrays and Python lists for a large-scale numerical operation:

```python
import numpy as np
import time

# Creating large arrays and lists
size = 1000000
arr = np.arange(size)
list_example = list(range(size))

# NumPy array operation
start = time.time()
arr_sum = np.sum(arr)
print("NumPy sum:", time.time() - start)

# Python list operation
start = time.time()
list_sum = sum(list_example)
print("List sum:", time.time() - start)
```

### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

**Comparing `vstack()` and `hstack()` in NumPy**

Both `vstack()` and `hstack()` are used to stack arrays, but they do so in different directions. Here's a detailed comparison:

**`vstack()`**
- **Purpose**: Stacks arrays in sequence vertically (row-wise).
- **Usage**: Useful when you want to add rows to an existing array.
- **Syntax**: `np.vstack(tup)`, where `tup` is a sequence of arrays to be stacked.

**Example**
```python
import numpy as np

# Creating two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])

# Stacking vertically
result = np.vstack((arr1, arr2))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
```

**`hstack()`**
- **Purpose**: Stacks arrays in sequence horizontally (column-wise).
- **Usage**: Useful when you want to add columns to an existing array.
- **Syntax**: `np.hstack(tup)`, where `tup` is a sequence of arrays to be stacked.

**Example**
```python
# Creating two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7], [8]])

# Stacking horizontally
result = np.hstack((arr1, arr2))
print(result)
# Output:
# [[1 2 3 7]
#  [4 5 6 8]]
```

**Key Differences**
1. **Direction of Stacking**:
   - `vstack()`: Stacks arrays vertically (adds rows).
   - `hstack()`: Stacks arrays horizontally (adds columns).

2. **Shape Requirements**:
   - `vstack()`: Arrays must have the same number of columns.
   - `hstack()`: Arrays must have the same number of rows.

### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

**Differences Between `fliplr()` and `flipud()` in NumPy**

Both `fliplr()` and `flipud()` are used to flip arrays, but they do so in different directions. Here's a detailed comparison:

**`fliplr()`**
- **Purpose**: Flips the array in the left/right direction (horizontally).
- **Effect**: Reverses the order of elements in each row, while preserving the columns.
- **Syntax**: `np.fliplr(m)`, where `m` is the input array.
- **Requirements**: The input array must be at least 2-dimensional.

**Example**
```python
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping horizontally
result = np.fliplr(arr)
print(result)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]
```

**`flipud()`**
- **Purpose**: Flips the array in the up/down direction (vertically).
- **Effect**: Reverses the order of elements in each column, while preserving the rows.
- **Syntax**: `np.flipud(m)`, where `m` is the input array.
- **Requirements**: The input array must be at least 1-dimensional.

**Example**
```python
# Flipping vertically
result = np.flipud(arr)
print(result)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
```

**Key Differences**

1. **Direction of Flip**:
   - `fliplr()`: Flips the array horizontally (left/right).
   - `flipud()`: Flips the array vertically (up/down).

2. **Dimensional Requirements**:
   - `fliplr()`: Requires the array to be at least 2-dimensional.
   - `flipud()`: Requires the array to be at least 1-dimensional.

**Effects on Various Array Dimensions**

- **1D Arrays**:
  - `fliplr()`: Not applicable (raises an error).
  - `flipud()`: Reverses the order of elements.
  - Example:
    ```python
    arr_1d = np.array([1, 2, 3])
    print(np.flipud(arr_1d))  # Output: [3 2 1]
    ```

- **2D Arrays**:
  - `fliplr()`: Reverses the order of elements in each row.
  - `flipud()`: Reverses the order of elements in each column.
  - Example:
    ```python
    arr_2d = np.array([[1, 2], [3, 4]])
    print(np.fliplr(arr_2d))
    # Output:
    # [[2 1]
    #  [4 3]]

    print(np.flipud(arr_2d))
    # Output:
    # [[3 4]
    #  [1 2]]
    ```

- **3D Arrays and Higher**:
  - Both functions can be applied, but the effect will depend on the specific axis being flipped.
  - Example:
    ```python
    arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
    print(np.fliplr(arr_3d))
    # Output:
    # [[[3 4]
    #   [1 2]]
    #  [[7 8]
    #   [5 6]]]

    print(np.flipud(arr_3d))
    # Output:
    # [[[5 6]
    #   [7 8]]
    #  [[1 2]
    #   [3 4]]]
    ```

### 9.  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

**Functionality of `array_split()` in NumPy**

The `array_split()` method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to divide an array into sections, especially when the division is not even.

**Syntax**
```python
numpy.array_split(ary, indices_or_sections, axis=0)
```
- **ary**: Input array to be split.
- **indices_or_sections**: If an integer, it indicates the number of equal or near-equal sub-arrays to be created. If a 1-D array of sorted integers, it indicates the indices at which to split.
- **axis**: The axis along which to split the array. Default is 0.

**Handling Uneven Splits**
The key feature of `array_split()` is its ability to handle uneven splits. When the array cannot be evenly divided by the specified number of sections, `array_split()` will create sub-arrays of nearly equal size. It ensures that the sub-arrays are as balanced as possible.

**Example with Uneven Split**
```python
import numpy as np

# Creating an array of 9 elements
arr = np.arange(9)

# Splitting into 4 parts
result = np.array_split(arr, 4)
print(result)
# Output:
# [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
```
In this example, the array of 9 elements is split into 4 parts. The first sub-array has 3 elements, while the remaining sub-arrays have 2 elements each.

**Comparison with `split()`**
- **`split()`**: Requires the array to be evenly divisible by the number of sections. If not, it raises an error.
- **`array_split()`**: Allows for uneven splits, making it more flexible.

**Example with `split()`**
```python
# This will raise an error because 9 is not evenly divisible by 4
try:
    result = np.split(arr, 4)
except ValueError as e:
    print(e)  # Output: array split does not result in an equal division
```

**Summary**
- **`array_split()`**: Flexible, handles uneven splits by creating sub-arrays of nearly equal size.
- **`split()`**: Strict, requires equal division, otherwise raises an error.

**Use Cases**
- **Data Partitioning**: When you need to partition data into training and testing sets of nearly equal size.
- **Batch Processing**: When processing data in batches that may not evenly divide the total dataset.

### 10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

**Vectorization in NumPy**

**Vectorization** refers to the process of performing operations on entire arrays without the need for explicit loops. This is achieved by leveraging NumPy's optimized, low-level implementations in C and Fortran, which are much faster than Python loops.

**Benefits of Vectorization**
1. **Performance**: Vectorized operations are significantly faster than their loop-based counterparts because they minimize the overhead of Python's interpreted loops.
2. **Code Simplicity**: Vectorized code is often more concise and easier to read, as it eliminates the need for explicit loops.
3. **Memory Efficiency**: Vectorized operations can be more memory-efficient, as they avoid the creation of intermediate arrays.

**Example**
```python
import numpy as np

# Using a loop to add two arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
result = np.zeros_like(arr1)
for i in range(len(arr1)):
    result[i] = arr1[i] + arr2[i]
print(result)  # Output: [6 6 6 6 6]

# Using vectorization to add two arrays
result = arr1 + arr2
print(result)  # Output: [6 6 6 6 6]
```

**Broadcasting in NumPy**

**Broadcasting** describes how NumPy handles arrays with different shapes during arithmetic operations. It allows NumPy to perform element-wise operations on arrays of different shapes by "stretching" the smaller array to match the shape of the larger array, without actually copying the data.

**Rules of Broadcasting**
1. **Dimensions Compatibility**: Two dimensions are compatible when they are equal or one of them is 1.
2. **Shape Matching**: NumPy compares the shapes of the arrays element-wise, starting from the trailing dimensions and working its way left.

**Benefits of Broadcasting**
1. **Memory Efficiency**: Broadcasting avoids the need to create large, intermediate arrays, saving memory.
2. **Performance**: By avoiding unnecessary data replication, broadcasting can lead to faster computations.
3. **Code Simplicity**: Broadcasting simplifies the code by allowing operations on arrays of different shapes without explicit reshaping.

**Example**
```python
# Broadcasting a scalar to an array
arr = np.array([1, 2, 3])
scalar = 2
result = arr * scalar
print(result)  # Output: [2 4 6]

# Broadcasting a 1D array to a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([1, 2, 3])
result = arr_2d + arr_1d
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]
```

**Contribution to Efficient Array Operations**

- **Vectorization**: Eliminates the need for explicit loops, leading to faster and more readable code.
- **Broadcasting**: Allows operations on arrays of different shapes without the need for explicit reshaping or copying, enhancing both performance and memory efficiency.

# Practical Questions :

#### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [6]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Transpose the array
transposed_arr = np.transpose(arr)
print("Transposed Array:")
print(transposed_arr)

Original Array:
[[29 31 53]
 [ 7 35 91]
 [53 58 55]]
Transposed Array:
[[29  7 53]
 [31 35 58]
 [53 91 55]]


#### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [8]:
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("1D Array:\n", array_1d)
print("2x5 Array:\n", array_2x5)
print("5x2 Array:\n", array_5x2)

1D Array:
 [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [10]:
# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array with random float values:\n", array_4x4)
print("6x6 Array with a border of zeros:\n", array_6x6)


4x4 Array with random float values:
 [[0.59096236 0.31588741 0.35488847 0.81991803]
 [0.31112697 0.61586243 0.42701048 0.48996082]
 [0.52315661 0.47196388 0.88355586 0.0049999 ]
 [0.5829734  0.38238881 0.94189429 0.00153598]]
6x6 Array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.59096236 0.31588741 0.35488847 0.81991803 0.        ]
 [0.         0.31112697 0.61586243 0.42701048 0.48996082 0.        ]
 [0.         0.52315661 0.47196388 0.88355586 0.0049999  0.        ]
 [0.         0.5829734  0.38238881 0.94189429 0.00153598 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [12]:
# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print("Array:", array)


Array: [10 15 20 25 30 35 40 45 50 55 60]


#### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [14]:
# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
swapcase_array = np.char.swapcase(array)

print("Original Array:", array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)
print("Swap Case:", swapcase_array)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Swap Case: ['PYTHON' 'NUMPY' 'PANDAS']


#### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [15]:
# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

print("Original Array:", words)
print("Array with spaces between characters:", spaced_words)


Original Array: ['python' 'numpy' 'pandas']
Array with spaces between characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


#### 7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [16]:
# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise subtraction
subtraction = np.subtract(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise division
division = np.divide(array1, array2)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


#### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [17]:
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


#### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [19]:
# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)

Random Integers:
 [ 30 254 812 148 757 980  10 272 884 565 823 702 608 818 235 473 776 809
  90 974 475 683 116 670 282 539 992 122 388 201 178 244  93 450 346 103
  22 370  75 510 235  59  74 712  84 916 964 327 624 216 382 428 134 322
 453  78 699 888 680 606 219 400 783 787 923 507 431 830 769 770 178  55
 530 372  73 990 996 780 530 665 528 892 708 406 740 417  12 244 886 545
 113 451 766 207 688 698 981  86 275 151]
Prime Numbers:
 [757, 823, 809, 683, 103, 59, 787, 431, 769, 73, 113, 151]


#### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [20]:


# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, size=30)  # Random temperatures between 20 and 40 degrees

# Calculate the weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

print("Daily Temperatures:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [24 38 21 21 38 38 38 30 31 26 28 37 23 39 34 22 33 35 23 24 39 23 36 20
 24 22 35 33 28 20]
Weekly Averages:
 [31.142857142857142, 30.571428571428573, 30.0, 27.571428571428573, 24.0]
