# NumPy Assigment 

In [6]:
import numpy as np

In [7]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

i = [i for i in range(1,100)]
arr  = np.random.choice(i,[3,3])
print(f" NumPy Array :\n\n {arr} \n Dimeansion Of Array :{arr.ndim} \n Shape Of Array : {arr.shape}\n Inter_Change Of Row and Columns :\n{arr.T}")


 NumPy Array :

 [[77 74 59]
 [11 53 53]
 [41 86 75]] 
 Dimeansion Of Array :2 
 Shape Of Array : (3, 3)
 Inter_Change Of Row and Columns :
[[77 11 41]
 [74 53 86]
 [59 53 75]]


In [77]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

arr1 = np.random.randint(1,100,(3,3))
arr1

array([[37, 27, 71],
       [74, 66, 96],
       [71, 43, 77]])

In [8]:
 # 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

# Generate The Array 
arr = np.arange(1,11)

print(f"Array : {arr} ")
print(f" Rows 2 and Columns 5 :\n {arr.reshape(2,5)} \n Shape Of The Array : {arr.reshape(2,5).shape}")
print(f" Rows 5 and Columns 2 :\n {arr.reshape(5,2)}\nShape Of The Array {arr.reshape(2,5).shape}")


Array : [ 1  2  3  4  5  6  7  8  9 10] 
 Rows 2 and Columns 5 :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 
 Shape Of The Array : (2, 5)
 Rows 5 and Columns 2 :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Shape Of The Array (2, 5)


In [35]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1,constant_values=0)

print("4x4 Array with random float values:\n", array_4x4)
print("\n6x6 Array with a border of zeros:\n", array_6x6)



4x4 Array with random float values:
 [[0.95572721 0.51237279 0.98836701 0.78695307]
 [0.11088076 0.10456967 0.61044107 0.80153499]
 [0.22958809 0.46090742 0.12970535 0.75102866]
 [0.73978746 0.6015395  0.11955167 0.89584201]]

6x6 Array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.95572721 0.51237279 0.98836701 0.78695307 0.        ]
 [0.         0.11088076 0.10456967 0.61044107 0.80153499 0.        ]
 [0.         0.22958809 0.46090742 0.12970535 0.75102866 0.        ]
 [0.         0.73978746 0.6015395  0.11955167 0.89584201 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [9]:
 # 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

# Here 10 is included and 60 is excluded
arr = np.arange(10,60,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [10]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
# (uppercase, lowercase, title case, etc.) to each element.

arr = np.array(['python', 'numpy', 'pandas'])

u = np.char.upper(arr)
l = np.char.lower(arr)
t = np.char.title(arr)
c = np.char.capitalize(arr)
s = np.sort(arr)

print(f"Original Arr {arr}\nUpper Case : {u}\nLower Case :{l}  \nTitle Case : {t} \nCapitalize Case : {c}\nSorted Array : {s}")

Original Arr ['python' 'numpy' 'pandas']
Upper Case : ['PYTHON' 'NUMPY' 'PANDAS']
Lower Case :['python' 'numpy' 'pandas']  
Title Case : ['Python' 'Numpy' 'Pandas'] 
Capitalize Case : ['Python' 'Numpy' 'Pandas']
Sorted Array : ['numpy' 'pandas' 'python']


In [38]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# Generate a NumPy array of words
words = np.array(["hello", "world", "numpy", "array", "example"])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

print("Original words:", words)
print("Spaced words:", spaced_words)



Original words: ['hello' 'world' 'numpy' 'array' 'example']
Spaced words: ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y' 'e x a m p l e']


In [39]:
 # 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division First Array 
arr1 = np.array([[1,2,],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(f"Addition : \n",np.add(arr1,arr2))
print(f"Substraction : \n",np.subtract(arr2,arr1))
print(f"Multiplication : \n",np.multiply(arr1,arr2))
print(f"Division : \n",arr1/arr2)

Addition : 
 [[ 6  8]
 [10 12]]
Substraction : 
 [[4 4]
 [4 4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [40]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np
identity_array_diff_no_row_columns = np.eye(2,3)
indentiy_array_same_no_row_columns = np.identity(5)
                                              # Sum Of the diagonal elements
# numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)

matrix = np.matrix('[11,2,3;4,5,6;7,8,9]')
print(matrix)
np.trace(matrix)


[[11  2  3]
 [ 4  5  6]
 [ 7  8  9]]


25

In [36]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, 100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random integers:", random_integers)
print("Prime numbers:", prime_numbers)


Random integers: [312 400 928 462  30 913 280 940 791 132 104 762 740 979 546 352 661 593
 225 496 672  12 242 264 786 887 811 593 445 446 674 835 542 587 762 131
 623 890 979 362 755 506 362 949 529 485 486 323 303 570  92 744 221 674
 626 700 463 781 709 271  60  85 485 236 141 990  36 373 498 530 616 440
 454 587 622 723 612 847 429  99 717 111 236 791 787 921 713 546 793 856
   2 994 766 457 361 790 327 745 364 108]
Prime numbers: [661, 593, 887, 811, 593, 587, 131, 463, 709, 271, 373, 587, 787, 2, 457]


In [ ]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

# Generate a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, 30)  # Example temperatures between 20°C and 40°C

# Calculate weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

print("Daily temperatures:", daily_temperatures)
print("Weekly averages:", weekly_averages) 